import type { Metadata } from "next";
import "./globals.css";

import { Urbanist} from "next/font/google"
import { Analytics } from "@vercel/analytics/react"

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['200', '400', '500', '600', '800'],
});

export const metadata: Metadata = {
  title: "Zetarya - Bulk data transfer",
  description: "Generated by create next appMoving world's data with speed, security and accuracy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={urbanist.className}>
      <body className="">{children}</body>
      <Analytics/>
    </html>
  );
}
